[package]
name = "actix_dailynotes"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
env_logger = "0.11.5"
log = "0.4.22"
serde = "1.0.210"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "migrate"] }
